packages:
  # specify a package in a direct subdir of the root
  # all packages in direct subdirs of packages/
  - 'main'
  - 'common-http'
  # all packages in subdirs of components/
  - 'web/**'

  # exclude packages that are inside test directories
